// Deterministic-but-varied mock "Generation details" for an asset (prototype
// only). Derived from the asset name's hash so a given asset always shows the
// same realistic-looking workflow / model / steps / prompt across the dock
// popover AND the tab details panel.

function hash(s: string) {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0
  return h
}
// NOTE: callers derive sub-indices with the UNSIGNED shift `>>>` (not `>>`) —
// a signed shift on a hash with the high bit set goes negative, and a negative
// index here returns `undefined`. `at` also normalises negatives defensively.
const at = <T,>(arr: readonly T[], n: number) => arr[((n % arr.length) + arr.length) % arr.length]!

// Mocked file size / created date derived from the name hash (no real metadata in
// the prototype). Same formulas the detail panels use, exported so the Quick Look
// preview shows consistent values. (The detail panels still keep local copies.)
export function mockSize(name: string) {
  return `${(2 + (hash(name) % 180) / 10).toFixed(1)} MB`
}
export function mockDate(name: string) {
  const h = hash(name)
  const d = new Date(2025, h % 12, (h % 28) + 1, h % 24, h % 60, (h >> 3) % 60)
  const date = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
  let hr = d.getHours()
  const ampm = hr >= 12 ? 'pm' : 'am'
  hr = hr % 12 || 12
  const time = `${hr}:${String(d.getMinutes()).padStart(2, '0')}:${String(d.getSeconds()).padStart(2, '0')}${ampm}`
  return { date, time }
}

/* ── Time-based media mocks (video / audio) ───────────────────────────────────
   Deterministic from the name hash so a clip/track always shows the same
   duration, fps, sample-rate, and waveform across the card, Quick Look, and the
   lightbox. No real media files in the prototype. */
export function mockDuration(name: string): string {
  const secs = 5 + (hash(name) % 596) // 5s .. ~10min
  const m = Math.floor(secs / 60)
  return `${m}:${String(secs % 60).padStart(2, '0')}`
}
const FPS = ['24fps', '30fps', '60fps'] as const
export const mockFps = (name: string) => at(FPS, hash(name) >>> 6)
const SAMPLE_RATES = ['44.1kHz', '48kHz'] as const
export const mockSampleRate = (name: string) => at(SAMPLE_RATES, hash(name) >>> 4)

// 3D model polygon count, e.g. "24k tris".
export const mockPolyCount = (name: string) => `${5 + (hash(name) % 142)}k tris`

/** Deterministic bar heights (0..1) for a fake audio waveform. An arch envelope
 *  (taller in the middle) over per-bar pseudo-random noise so it reads as audio. */
export function mockWaveform(name: string, bars = 48): number[] {
  let seed = hash(name) || 1
  const out: number[] = []
  for (let i = 0; i < bars; i++) {
    seed = (seed * 1103515245 + 12345) >>> 0
    const noise = (seed % 1000) / 1000 // 0..1
    const arch = 0.4 + 0.6 * Math.sin((Math.PI * i) / (bars - 1)) // 0.4..1
    out.push(Math.max(0.1, noise * arch))
  }
  return out
}

// Exported so the "Model type" filter can offer the same models assets are
// actually generated with (see gallery/filters.ts).
export const MODELS = [
  'Flux.1 dev',
  'Flux.1 schnell',
  'SDXL 1.0',
  'SD 1.5',
  'Juggernaut XL v9',
  'DreamShaper XL',
  'RealVisXL V4.0',
  'Playground v2.5',
  'SD 3.5 Large',
  'Pony Diffusion V6 XL',
] as const

const WORKFLOWS = [
  'txt2img',
  'SDXL portrait',
  'img2img refine',
  'ControlNet depth',
  'Inpaint cleanup',
  'LoRA character',
  'Detail daemon',
  'Style transfer',
] as const

// Pure upscale / hi-res passes take no text prompt — assets generated by these
// legitimately have NO prompt, so the Prompt field is hidden entirely.
const PROMPTLESS_WORKFLOWS = ['Flux upscale ×2', 'Hires fix', 'Latent upscale ×1.5'] as const

const PROMPTS = [
  'A serene alpine lake at sunrise, mist over the water, volumetric light, ultra-detailed, 8k',
  'Studio portrait of a woman with freckles, soft rim lighting, 85mm, shallow depth of field, photorealistic',
  'Neon-lit cyberpunk alley in the rain, reflections on wet pavement, cinematic, moody, highly detailed',
  'Cozy scandinavian living room, warm morning light, houseplants, film grain, editorial interior photography',
  'Dense snowy pine forest at dusk, fog rolling between the trees, dramatic, fine-art landscape',
  // A couple of intentionally long prompts to stress-test wrapping / scroll.
  'A sweeping cinematic wide shot of a futuristic megacity at dusk, towering glass skyscrapers wrapped in holographic advertisements, flying vehicles streaking between the buildings, dense neon signage, rain-slicked streets reflecting magenta and cyan light, dramatic god rays breaking through low clouds, a lone figure in a long coat on a rooftop, shot on 35mm anamorphic, shallow depth of field, volumetric fog, ultra detailed, photorealistic, 8k',
  'Minimalist product shot of a glass perfume bottle on polished marble, soft shadows, high-key studio lighting',
  'Golden retriever puppy running through a field of wildflowers, sunny afternoon, bokeh, 50mm',
  'Highly detailed fantasy concept art of an ancient overgrown temple deep in the jungle, massive moss-covered stone pillars, shafts of golden sunlight filtering through the dense canopy, exotic birds and glowing fireflies drifting through the air, a crumbling staircase leading up to a softly glowing artifact, lush ferns and hanging vines everywhere, atmospheric haze, painterly brushwork, intricate ornamentation, dramatic composition, matte painting, trending on artstation',
  'Vintage film still of a desert highway at golden hour, lens flare, 35mm, warm tones',
] as const

export interface Generation {
  workflow: string
  model: string
  steps: number
  /** Absent for promptless workflows (upscale / hi-res passes) — hide the field. */
  prompt?: string
}

export function mockGeneration(name: string): Generation {
  const h = hash(name)
  const model = at(MODELS, h)
  const fast = /schnell|turbo|lightning/i.test(model)
  // ~1 in 5 assets is a promptless upscale/hi-res pass (Prompt field hidden).
  const promptless = (h >>> 11) % 5 === 0
  return {
    workflow: promptless ? at(PROMPTLESS_WORKFLOWS, h >>> 5) : at(WORKFLOWS, h >>> 5),
    model,
    // schnell/turbo run at very low step counts; everything else 20–50.
    steps: fast ? at([4, 6, 8], h >>> 2) : at([20, 24, 28, 30, 35, 40, 50], h >>> 2),
    prompt: promptless ? undefined : at(PROMPTS, h >>> 9),
  }
}
